FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install build-essential git npm -y

RUN apt-get install curl sudo -y

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 10.24.1

WORKDIR $NVM_DIR

RUN curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

ENV NODE_PATH $NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
RUN node -v

RUN npm install --global yarn

RUN git clone https://github.com/substrate-developer-hub/substrate-front-end-template

WORKDIR substrate-front-end-template


RUN yarn install
RUN yarn add @polkadot/api-contract


CMD ["yarn", "start"]